(() => {
"use strict";
const SUPABASE_URL="https://yiqxylckxkjnmenmykik.supabase.co",SUPABASE_KEY="sb_publishable_8tH2zh33We3vWO7sk9vrtA_VUWQH9NX",SCORE_TABLE="travel_universe_scores";
const $=id=>document.getElementById(id),canvas=$("game"),ctx=canvas.getContext("2d");
const worlds=[
{name:"Grasslands",need:0,mult:1,sky:"#87ceeb",ground:"#45a049"},{name:"Desert",need:1000,mult:2,sky:"#f1cf72",ground:"#c49a35"},{name:"Snow",need:5000,mult:4,sky:"#d8f0ff",ground:"#e7f7ff"},{name:"Volcano",need:15000,mult:7,sky:"#6f2d1f",ground:"#2c1b17"},{name:"City",need:40000,mult:12,sky:"#8892a0",ground:"#444"},{name:"Cyber",need:100000,mult:20,sky:"#10102f",ground:"#15206e"},{name:"Space",need:250000,mult:40,sky:"#050518",ground:"#333"},{name:"Nebula",need:600000,mult:80,sky:"#4b1d66",ground:"#251032"},{name:"Black Hole",need:1500000,mult:150,sky:"#050505",ground:"#141414"},{name:"Universe's End",need:4000000,mult:300,sky:"#000",ground:"#2a002a"}
];
const guns={pistol:{name:"Pistol",cost:0,damage:1,rate:.32,speed:700,pellets:1,spread:0,pierce:0},smg:{name:"SMG",cost:4000,damage:.65,rate:.1,speed:760,pellets:1,spread:.08,pierce:0},shotgun:{name:"Shotgun",cost:12000,damage:.75,rate:.75,speed:620,pellets:7,spread:.42,pierce:0},sniper:{name:"Sniper",cost:30000,damage:5,rate:1.2,speed:1100,pellets:1,spread:0,pierce:3}};
const skins=[{id:"blue",name:"Blue",color:"#2288ff",cost:0},{id:"gold",name:"Gold",color:"#ffd700",cost:5000},{id:"red",name:"Red",color:"#ff3333",cost:15000},{id:"lime",name:"Lime",color:"#66ff44",cost:50000},{id:"matrix",name:"Matrix",color:"#00ffaa",cost:200000},{id:"void",name:"Void",color:"#662299",cost:1000000}];
const boosts=[{id:"money",name:"2x Money (2 min)",cost:2500,duration:120},{id:"speed",name:"2x Speed (1 min)",cost:5000,duration:60},{id:"damage",name:"2x Damage (2 min)",cost:7500,duration:120}];
const companions=[{id:"blueBuddy",name:"Blue Buddy",cost:25000,desc:"Shoots nearby zombies"},{id:"goldBuddy",name:"Gold Buddy",cost:50000,desc:"+15% money"},{id:"medicBuddy",name:"Medic Buddy",cost:80000,desc:"Reduces zombie collision loss"}];
const defaults={money:0,runDistance:0,bestDistance:0,totalDistance:0,speedLevel:0,incomeLevel:0,rockLevel:0,damageLevel:0,rebirths:0,kills:0,crates:0,bossKills:0,ownedSkins:["blue"],skin:"blue",ownedGuns:["pistol"],gun:"pistol",ownedCompanions:[],boosts:{money:0,speed:0,damage:0},usedCodes:[],playerName:"CubePlayer",playTime:0};
let save=load(),paused=false,last=performance.now(),bullets=[],zombies=[],particles=[],crates=[],eventsIn=35,activeEvent=null,zombieTimer=0,bossTimer=75,crateTimer=25,shotCooldown=0,dashCooldown=0,screenShake=0,runTime=0,boulderSpawned=false,boulderWarning=false,keys={},pointer={x:800,y:300,down:false};
const player={x:260,y:370,size:34,vx:0,vy:0},boulder={x:-180,y:387,radius:60,speed:0};
function load(){try{let d=JSON.parse(localStorage.getItem("ttdu.save.v2")||localStorage.getItem("ttdu.save.v1"));return {...structuredClone(defaults),...(d||{}),boosts:{...defaults.boosts,...(d?.boosts||{})}}}catch{return structuredClone(defaults)}}
function persist(){localStorage.setItem("ttdu.save.v2",JSON.stringify(save))}
const fmt=n=>{if(n<1000)return Math.floor(n).toLocaleString();let u=["K","M","B","T","Qa","Qi"],i=-1;while(n>=1000&&i<u.length-1){n/=1000;i++}return n.toFixed(n>=100?0:n>=10?1:2)+u[i]},dist=m=>m<1000?Math.floor(m)+" m":(m/1000).toFixed(m<10000?2:1)+" km";
const worldIndex=()=>{let i=0;worlds.forEach((w,n)=>{if(save.bestDistance>=w.need)i=n});return i},speedBase=()=>1+save.speedLevel*.15,speedMult=()=>(1+save.rebirths*.05)*(save.boosts.speed>0?2:1),actualSpeed=()=>speedBase()*speedMult(),incomeBase=()=>1+save.incomeLevel*2.5,moneyMult=()=>worlds[worldIndex()].mult*(save.boosts.money>0?2:1)*(activeEvent?.type==="money"?3:1)*(save.ownedCompanions.includes("goldBuddy")?1.15:1),income=()=>incomeBase()*moneyMult(),rockLimit=()=>700+save.rockLevel*260,rebirthNeed=()=>Math.floor(1500*Math.pow(1.72,save.rebirths)),cost=(base,pow,lvl)=>Math.floor(base*Math.pow(pow,lvl));
function spend(c){if(save.money<c)return false;save.money-=c;return true}
function banner(t){const b=$("eventBanner");b.textContent=t;b.hidden=false;setTimeout(()=>b.hidden=true,3000)}
function spawnZombie(type){let wi=worldIndex(),z={x:canvas.width+50,y:320+Math.random()*155,size:30,hp:2+Math.floor(wi/2)+Math.floor(save.rebirths/4),speed:42+wi*5,reward:(18+wi*10)*worlds[wi].mult,type:type||"normal"};if(z.type==="fast"){z.size=23;z.speed*=1.8;z.hp*=.65}if(z.type==="tank"){z.size=48;z.speed*=.55;z.hp*=4;z.reward*=3}if(z.type==="exploder"){z.size=32;z.speed*=1.1;z.reward*=2}if(z.type==="boss"){z.size=88;z.speed*=.45;z.hp*=18;z.reward*=18}z.maxHp=z.hp;zombies.push(z)}
function fire(tx,ty,auto=false){if(paused||shotCooldown>0)return;let g=guns[save.gun],px=player.x+player.size/2,py=player.y+player.size/2,base=Math.atan2(ty-py,tx-px);for(let i=0;i<g.pellets;i++){let a=base+(Math.random()-.5)*g.spread;bullets.push({x:px,y:py,vx:Math.cos(a)*g.speed,vy:Math.sin(a)*g.speed,life:1.5,damage:g.damage*(1+save.damageLevel*.25)*(save.boosts.damage>0?2:1),pierce:g.pierce})}shotCooldown=g.rate;if(!auto)pointer.down=true}
function point(e){let r=canvas.getBoundingClientRect();pointer.x=(e.clientX-r.left)*canvas.width/r.width;pointer.y=(e.clientY-r.top)*canvas.height/r.height}
canvas.addEventListener("pointerdown",e=>{point(e);pointer.down=true;fire(pointer.x,pointer.y)});canvas.addEventListener("pointermove",point);window.addEventListener("pointerup",()=>pointer.down=false);
window.addEventListener("keydown",e=>{keys[e.key.toLowerCase()]=true;if(e.code==="Space"){e.preventDefault();dash()}});window.addEventListener("keyup",e=>keys[e.key.toLowerCase()]=false);
document.querySelectorAll("[data-move]").forEach(b=>{let k=b.dataset.move;b.addEventListener("pointerdown",()=>keys[k]=true);b.addEventListener("pointerup",()=>keys[k]=false);b.addEventListener("pointerleave",()=>keys[k]=false)});
function dash(){if(dashCooldown>0||paused)return;player.x=Math.min(420,player.x+90);dashCooldown=6;screenShake=4;banner("DASH!")}
$("dashBtn").onclick=dash;
function crush(){paused=true;screenShake=18;save.runDistance=0;runTime=0;boulderSpawned=false;boulderWarning=false;boulder.x=-180;zombies=[];bullets=[];crates=[];persist();$("crushMessage").hidden=false}
$("continueBtn").onclick=()=>{paused=false;$("crushMessage").hidden=true};
function event(){let choices=[{type:"money",name:"Money Storm: 3x money",time:25},{type:"speed",name:"Speed Surge",time:20},{type:"horde",name:"Zombie Horde",time:22},{type:"freeze",name:"Boulder Freeze",time:15},{type:"lucky",name:"Lucky Day: more crates",time:20}];activeEvent=choices[Math.floor(Math.random()*choices.length)];banner(activeEvent.name)}
function spawnCrate(){crates.push({x:canvas.width+20,y:350+Math.random()*100,size:28})}
function update(dt){if(paused)return;runTime+=dt;save.playTime+=dt;shotCooldown=Math.max(0,shotCooldown-dt);dashCooldown=Math.max(0,dashCooldown-dt);Object.keys(save.boosts).forEach(k=>save.boosts[k]=Math.max(0,save.boosts[k]-dt));
if(pointer.down&&guns[save.gun].rate<.2)fire(pointer.x,pointer.y);
let mx=(keys.d||keys.arrowright||keys.right?1:0)-(keys.a||keys.arrowleft||keys.left?1:0),my=(keys.s||keys.arrowdown||keys.down?1:0)-(keys.w||keys.arrowup||keys.up?1:0);player.vx+=(mx*130-player.vx)*Math.min(1,dt*8);player.vy+=(my*180-player.vy)*Math.min(1,dt*8);player.x=Math.max(180,Math.min(420,player.x+player.vx*dt));player.y=Math.max(250,Math.min(478-player.size,player.y+player.vy*dt));
if(runTime>25&&!boulderWarning){boulderWarning=true;banner("THE BOULDER ARRIVES IN 5 SECONDS")}
if(runTime>=30&&!boulderSpawned){boulderSpawned=true;boulder.x=-160;boulder.y=player.y+player.size/2;boulder.speed=45;screenShake=8;banner("THE BOULDER HAS STARTED ROLLING!")}
let evs=activeEvent?.type==="speed"?1.5:1,gain=actualSpeed()*evs*18*dt;save.runDistance+=gain;save.totalDistance+=gain;save.bestDistance=Math.max(save.bestDistance,save.runDistance);save.money+=income()*dt;
if(boulderSpawned){boulder.y+=(player.y+player.size/2-boulder.y)*Math.min(1,dt*7);if(activeEvent?.type!=="freeze"){let chase=45+runTime*.55+save.rebirths*1.2;boulder.x+=chase*dt}if(boulder.x+boulder.radius>=player.x)crush()}
eventsIn-=dt;if(eventsIn<=0){event();eventsIn=45+Math.random()*30}if(activeEvent&&(activeEvent.time-=dt)<=0)activeEvent=null;
zombieTimer-=dt;if(zombieTimer<=0){let r=Math.random(),t=r<.12?"fast":r<.2?"tank":r<.27?"exploder":"normal";spawnZombie(t);zombieTimer=activeEvent?.type==="horde"?.38:Math.max(.75,2.1-worldIndex()*.09)}
bossTimer-=dt;if(bossTimer<=0){spawnZombie("boss");banner("BOSS ZOMBIE!");bossTimer=90}
crateTimer-=dt;if(crateTimer<=0){spawnCrate();crateTimer=activeEvent?.type==="lucky"?8:28+Math.random()*18}
bullets.forEach(b=>{b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt});bullets=bullets.filter(b=>b.life>0&&b.x<1030&&b.y>-30&&b.y<570);
zombies.forEach(z=>{let a=Math.atan2(player.y-z.y,player.x-z.x);z.x+=Math.cos(a)*z.speed*dt;z.y+=Math.sin(a)*z.speed*dt});
for(const b of bullets)for(const z of zombies){if(z.hp<=0||b.life<=0)continue;if(Math.hypot(b.x-z.x,b.y-z.y)<z.size/2+6){let crit=Math.random()<.1;z.hp-=b.damage*(crit?2:1);if(b.pierce>0)b.pierce--;else b.life=0;if(z.hp<=0){save.kills++;save.money+=z.reward;if(z.type==="boss")save.bossKills++;if(z.type==="exploder")zombies.forEach(o=>{if(o!==z&&Math.hypot(o.x-z.x,o.y-z.y)<110)o.hp-=4});for(let i=0;i<8;i++)particles.push({x:z.x,y:z.y,vx:(Math.random()-.5)*150,vy:(Math.random()-.5)*150,life:.45})}}}
zombies=zombies.filter(z=>z.hp>0&&z.x>-80);for(const z of zombies){if(Math.abs(z.x-player.x)<(z.size+player.size)/2&&Math.abs(z.y-player.y)<(z.size+player.size)/2){let loss=Math.max(10,income()*3)*(save.ownedCompanions.includes("medicBuddy")?.5:1);save.money=Math.max(0,save.money-loss);z.hp=0;screenShake=7}}
crates.forEach(c=>c.x-=120*dt);for(const c of crates){if(Math.abs(c.x-player.x)<45&&Math.abs(c.y-player.y)<50){save.crates++;save.money+=income()*20;c.got=true;banner("SUPPLY CRATE! +$"+fmt(income()*20))}}crates=crates.filter(c=>!c.got&&c.x>-40);
if(save.ownedCompanions.includes("blueBuddy")&&zombies.length){let z=zombies.reduce((a,b)=>b.x<a.x?b:a,zombies[0]);if(Math.random()<dt*1.2)fire(z.x,z.y,true)}
particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt});particles=particles.filter(p=>p.life>0)}
function draw(){let w=worlds[worldIndex()];ctx.save();if(screenShake>0){ctx.translate((Math.random()-.5)*screenShake,(Math.random()-.5)*screenShake);screenShake*=.84}ctx.fillStyle=w.sky;ctx.fillRect(0,0,960,540);ctx.fillStyle=w.ground;ctx.fillRect(0,420,960,120);ctx.fillStyle="rgba(255,255,255,.55)";for(let i=0;i<10;i++)ctx.fillRect(i*170-(save.runDistance*.5)%170,455,80,5);
if(boulderSpawned){ctx.fillStyle="#666";ctx.beginPath();ctx.arc(boulder.x,boulder.y,boulder.radius,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#333";ctx.lineWidth=5;ctx.stroke()}
ctx.fillStyle=skins.find(s=>s.id===save.skin)?.color||"#2288ff";ctx.fillRect(player.x,player.y,player.size,player.size);ctx.strokeStyle="#000";ctx.strokeRect(player.x,player.y,player.size,player.size);ctx.fillStyle="#111";ctx.fillRect(player.x+18,player.y+11,28,7);
let ang=performance.now()/600;save.ownedCompanions.forEach((id,i)=>{ctx.fillStyle=id==="goldBuddy"?"#ffd700":id==="medicBuddy"?"#fff":"#55aaff";ctx.fillRect(player.x+Math.cos(ang+i*2.1)*55,player.y+Math.sin(ang+i*2.1)*38,14,14)});
bullets.forEach(b=>{ctx.fillStyle="#ffeb3b";ctx.beginPath();ctx.arc(b.x,b.y,5,0,Math.PI*2);ctx.fill()});crates.forEach(c=>{ctx.fillStyle="#9b6b32";ctx.fillRect(c.x-14,c.y-14,28,28);ctx.strokeStyle="#fff";ctx.strokeRect(c.x-14,c.y-14,28,28)});
zombies.forEach(z=>{ctx.fillStyle=z.type==="fast"?"#79d65a":z.type==="tank"?"#295c31":z.type==="exploder"?"#d6a33c":z.type==="boss"?"#7d1f1f":"#3f9b45";ctx.fillRect(z.x-z.size/2,z.y-z.size/2,z.size,z.size);ctx.fillStyle="#111";ctx.fillRect(z.x-8,z.y-8,5,5);ctx.fillRect(z.x+3,z.y-8,5,5);ctx.fillStyle="#b00";ctx.fillRect(z.x-z.size/2,z.y-z.size/2-8,z.size,4);ctx.fillStyle="#0f0";ctx.fillRect(z.x-z.size/2,z.y-z.size/2-8,z.size*(z.hp/z.maxHp),4)});particles.forEach(p=>{ctx.fillStyle="#ffe066";ctx.fillRect(p.x,p.y,4,4)});
ctx.fillStyle="rgba(0,0,0,.65)";ctx.fillRect(10,10,370,92);ctx.fillStyle="#fff";ctx.font="17px Arial";ctx.fillText(w.name+"  x"+w.mult+" money",20,35);ctx.fillText(boulderSpawned?"Boulder gap: "+Math.max(0,Math.floor(player.x-boulder.x-boulder.radius))+" px":"Boulder in: "+Math.max(0,Math.ceil(30-runTime))+"s",20,60);ctx.fillText("Run: "+dist(save.runDistance)+"  Gun: "+guns[save.gun].name,20,85);ctx.restore()}
function ui(){$("money").textContent=fmt(save.money);$("distance").textContent=dist(save.runDistance);$("speedStat").textContent=actualSpeed().toFixed(2);$("worldStat").textContent=(worldIndex()+1)+" - "+worlds[worldIndex()].name;$("rebirthStat").textContent=save.rebirths;$("killStat").textContent=save.kills;
let sc=cost(25,1.55,save.speedLevel),ic=cost(35,1.58,save.incomeLevel),rc=cost(60,1.62,save.rockLevel),dc=cost(80,1.6,save.damageLevel);$("upgradeSpeed").textContent=`Speed Lv ${save.speedLevel} - $${fmt(sc)}`;$("upgradeIncome").textContent=`Money/sec Lv ${save.incomeLevel} - $${fmt(ic)}`;$("upgradeRock").textContent=`Rock Gap Lv ${save.rockLevel} - $${fmt(rc)}`;$("upgradeDamage").textContent=`Damage Lv ${save.damageLevel} - $${fmt(dc)}`;$("rebirthBtn").textContent=`Rebirth at ${dist(rebirthNeed())}`;$("rebirthBtn").disabled=save.runDistance<rebirthNeed();$("rockInfo").textContent=`Rock starts at 30s. Run capacity: ${dist(rockLimit())}`;let ab=Object.entries(save.boosts).filter(([,v])=>v>0).map(([k,v])=>`${k} ${Math.ceil(v)}s`).join(", ");$("boostInfo").textContent=ab?"Boosts: "+ab:"Boosts: none";$("challengeInfo").textContent=`Challenge: kill ${25+save.rebirths*10} zombies (${save.kills%(25+save.rebirths*10)}/${25+save.rebirths*10})`;$("dashBtn").textContent=dashCooldown>0?`DASH ${dashCooldown.toFixed(1)}s`:"DASH";$("gunInfo").textContent=`Damage ${guns[save.gun].damage} | Fire rate ${guns[save.gun].rate}s`}
function loop(n){let dt=Math.min(.05,(n-last)/1000);last=n;update(dt);draw();ui();requestAnimationFrame(loop)}
function buyBtn(id,fn){$(id).onclick=fn}buyBtn("upgradeSpeed",()=>{let c=cost(25,1.55,save.speedLevel);if(spend(c))save.speedLevel++});buyBtn("upgradeIncome",()=>{let c=cost(35,1.58,save.incomeLevel);if(spend(c))save.incomeLevel++});buyBtn("upgradeRock",()=>{let c=cost(60,1.62,save.rockLevel);if(spend(c))save.rockLevel++});buyBtn("upgradeDamage",()=>{let c=cost(80,1.6,save.damageLevel);if(spend(c))save.damageLevel++});$("rebirthBtn").onclick=()=>{if(save.runDistance>=rebirthNeed()){save.rebirths++;save.runDistance=0;runTime=0;boulderSpawned=false;boulderWarning=false;boulder.x=-180;zombies=[];bullets=[];banner("REBIRTH! Permanent +5% speed")}};
function refreshGunSelect(){let s=$("gunSelect");s.innerHTML="";save.ownedGuns.forEach(id=>{let o=document.createElement("option");o.value=id;o.textContent=guns[id].name;s.appendChild(o)});s.value=save.gun}s=$("gunSelect");s.onchange=()=>save.gun=s.value;refreshGunSelect();
function open(id){$(id).showModal()}$("shopBtn").onclick=()=>{renderShop("guns");open("shopDialog")};$("codesBtn").onclick=()=>open("codesDialog");$("leaderboardBtn").onclick=()=>{$("playerName").value=save.playerName;open("leaderboardDialog");loadScores()};$("statsBtn").onclick=()=>{renderStats();open("statsDialog")};$("helpBtn").onclick=()=>open("helpDialog");document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>$(b.dataset.close).close());document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>renderShop(b.dataset.tab));
function renderShop(tab){let c=$("shopContent");c.innerHTML="";let list=tab==="guns"?Object.entries(guns).map(([id,x])=>({...x,id,type:"gun"})):tab==="skins"?skins.map(x=>({...x,type:"skin"})):tab==="boosts"?boosts.map(x=>({...x,type:"boost"})):companions.map(x=>({...x,type:"comp"}));list.forEach(x=>{let d=document.createElement("div");d.className="shop-item";d.innerHTML=`<b>${x.name}</b><p>${x.desc||("Cost: $"+fmt(x.cost))}</p>`;let b=document.createElement("button");if(x.type==="gun"){let own=save.ownedGuns.includes(x.id);b.textContent=own?(save.gun===x.id?"Equipped":"Equip"):"Buy $"+fmt(x.cost);b.disabled=save.gun===x.id;b.onclick=()=>{if(!own){if(!spend(x.cost))return;save.ownedGuns.push(x.id)}save.gun=x.id;refreshGunSelect();renderShop(tab)}}else if(x.type==="skin"){let own=save.ownedSkins.includes(x.id);b.textContent=own?(save.skin===x.id?"Equipped":"Equip"):"Buy $"+fmt(x.cost);b.disabled=save.skin===x.id;b.onclick=()=>{if(!own){if(!spend(x.cost))return;save.ownedSkins.push(x.id)}save.skin=x.id;renderShop(tab)}}else if(x.type==="boost"){b.textContent="Buy $"+fmt(x.cost);b.onclick=()=>{if(spend(x.cost)){save.boosts[x.id]+=x.duration;renderShop(tab)}}}else{let own=save.ownedCompanions.includes(x.id);b.textContent=own?"Owned":"Buy $"+fmt(x.cost);b.disabled=own;b.onclick=()=>{if(spend(x.cost)){save.ownedCompanions.push(x.id);renderShop(tab)}}}d.appendChild(b);c.appendChild(d)})}
function renderStats(){$("statsContent").innerHTML=`<p>Best distance: ${dist(save.bestDistance)}</p><p>Total distance: ${dist(save.totalDistance)}</p><p>Zombies defeated: ${save.kills}</p><p>Bosses defeated: ${save.bossKills}</p><p>Crates collected: ${save.crates}</p><p>Play time: ${Math.floor(save.playTime/60)} minutes</p><p>Guns: ${save.ownedGuns.length}/${Object.keys(guns).length}</p><p>Skins: ${save.ownedSkins.length}/${skins.length}</p><p>Companions: ${save.ownedCompanions.length}/${companions.length}</p>`}
const codeRewards={FIRSTSTEP:{money:2500,msg:"+$2,500"},BIGROCK:{money:5000,rock:1,msg:"+$5,000 and +1 rock level"},CUBEPOWER:{money:10000,speed:1,msg:"+$10,000 and +1 speed level"},GUNRUNNER:{money:8000,damage:1,msg:"+$8,000 and +1 damage level"}};$("redeemCode").onclick=()=>{let code=$("codeInput").value.trim().toUpperCase(),o=$("codeMessage"),r=codeRewards[code];if(!r)return o.textContent="Invalid code.";if(save.usedCodes.includes(code))return o.textContent="Already used.";save.money+=r.money||0;save.rockLevel+=r.rock||0;save.speedLevel+=r.speed||0;save.damageLevel+=r.damage||0;save.usedCodes.push(code);o.textContent="Redeemed: "+r.msg;persist()};
async function loadScores(){let l=$("leaderboardList"),m=$("leaderboardMessage");l.innerHTML="";m.textContent="Loading...";try{let r=await fetch(`${SUPABASE_URL}/rest/v1/${SCORE_TABLE}?select=name,distance,rebirths&order=distance.desc&limit=20`,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`}});if(!r.ok)throw Error();let rows=await r.json();rows.forEach(x=>{let li=document.createElement("li");li.textContent=`${x.name} — ${dist(Number(x.distance))} — ${x.rebirths} rebirths`;l.appendChild(li)});m.textContent=rows.length?"Top distances":"No scores yet."}catch{m.textContent="Leaderboard table is not ready."}}
$("submitScore").onclick=async()=>{let name=$("playerName").value.trim().slice(0,20)||"CubePlayer";save.playerName=name;try{let r=await fetch(`${SUPABASE_URL}/rest/v1/${SCORE_TABLE}`,{method:"POST",headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,"Content-Type":"application/json",Prefer:"return=minimal"},body:JSON.stringify({name,distance:Math.floor(save.bestDistance),rebirths:save.rebirths,money:Math.floor(save.money)})});if(!r.ok)throw Error();$("leaderboardMessage").textContent="Score submitted!";loadScores()}catch{$("leaderboardMessage").textContent="Could not submit."}};$("refreshScores").onclick=loadScores;
window.addEventListener("beforeunload",persist);setInterval(persist,5000);requestAnimationFrame(loop);
})();
