(()=>{"use strict";
const SUPABASE_URL="https://yiqxylckxkjnmenmykik.supabase.co",SUPABASE_KEY="sb_publishable_8tH2zh33We3vWO7sk9vrtA_VUWQH9NX",SCORE_TABLE="travel_universe_scores";
const $=id=>document.getElementById(id),canvas=$("game"),ctx=canvas.getContext("2d"),editorCanvas=$("editorCanvas"),ectx=editorCanvas.getContext("2d");
const worlds=[
{name:"Grasslands",need:0,mult:1,sky:"#87ceeb",ground:"#45a049"},{name:"Flower Fields",need:900,mult:1.7,sky:"#9ad8ff",ground:"#72b94d"},{name:"Desert",need:3000,mult:3,sky:"#f1cf72",ground:"#c49a35"},{name:"Snow",need:9000,mult:5,sky:"#d8f0ff",ground:"#e7f7ff"},{name:"Volcano",need:24000,mult:9,sky:"#6f2d1f",ground:"#2c1b17"},{name:"City",need:65000,mult:15,sky:"#8892a0",ground:"#444"},{name:"Cyber",need:160000,mult:28,sky:"#10102f",ground:"#15206e"},{name:"Space",need:400000,mult:55,sky:"#050518",ground:"#333"},{name:"Nebula",need:950000,mult:100,sky:"#4b1d66",ground:"#251032"},{name:"Universe's End",need:2500000,mult:220,sky:"#000",ground:"#2a002a"}
];
const guns={
pistol:{name:"Pistol",cost:0,damage:1,rate:.32,speed:720,pellets:1,spread:0,pierce:0,color:"#ffe66d"},
smg:{name:"SMG",cost:4000,damage:.7,rate:.095,speed:780,pellets:1,spread:.09,pierce:0,color:"#fff176"},
shotgun:{name:"Shotgun",cost:12000,damage:.8,rate:.72,speed:640,pellets:7,spread:.46,pierce:0,color:"#ffca63"},
sniper:{name:"Sniper",cost:30000,damage:5.5,rate:1.15,speed:1200,pellets:1,spread:0,pierce:4,color:"#7cecff"},
burst:{name:"Burst Rifle",cost:55000,damage:1.3,rate:.2,speed:900,pellets:3,spread:.08,pierce:0,color:"#a8ff8d"},
laser:{name:"Laser",cost:120000,damage:1.1,rate:.065,speed:1450,pellets:1,spread:0,pierce:2,color:"#ff4dff"},
rocket:{name:"Rocket Launcher",cost:260000,damage:10,rate:1.35,speed:520,pellets:1,spread:0,pierce:0,blast:115,color:"#ff7b4d"},
minigun:{name:"Minigun",cost:600000,damage:.75,rate:.045,speed:980,pellets:1,spread:.16,pierce:0,color:"#fff"},
lightning:{name:"Lightning Gun",cost:1400000,damage:3.5,rate:.38,speed:1100,pellets:1,spread:.04,pierce:5,color:"#69eaff"},
cubeCannon:{name:"Cube Cannon",cost:4000000,damage:20,rate:1.8,speed:460,pellets:1,spread:0,pierce:8,blast:150,color:"#69ff86"}
};
const boosts=[{id:"money",name:"2x Money (2 min)",cost:2500,duration:120},{id:"speed",name:"2x Speed (1 min)",cost:5000,duration:60},{id:"damage",name:"2x Damage (2 min)",cost:7500,duration:120}];
const companions=[{id:"blueBuddy",name:"Blue Buddy",cost:25000,desc:"Shoots nearby zombies"},{id:"goldBuddy",name:"Gold Buddy",cost:50000,desc:"+15% money"},{id:"medicBuddy",name:"Medic Buddy",cost:80000,desc:"Halves collision losses"}];
const parts={
legs:[{id:"leg",name:"Basic Leg",cost:1200,desc:"+2% speed",speed:.02},{id:"springLeg",name:"Spring Leg",cost:9000,desc:"+5% speed, +8% dash",speed:.05,dash:.08},{id:"machineLeg",name:"Mechanical Leg",cost:35000,desc:"+8% speed, boulder +1%",speed:.08,rock:.01}],
arms:[{id:"arm",name:"Basic Arm",cost:1800,desc:"+3% damage",damage:.03},{id:"gunArm",name:"Gun Arm",cost:14000,desc:"+5% fire rate",rate:.05},{id:"tentacle",name:"Tentacle Arm",cost:60000,desc:"+6% damage and crit",damage:.06,crit:.01}],
fungus:[{id:"fungus",name:"Cube Fungus",cost:3000,desc:"+4% income",income:.04},{id:"gunFungus",name:"Gun Fungus",cost:22000,desc:"Occasionally fires",autofire:.18},{id:"unstableFungus",name:"Unstable Growth",cost:85000,desc:"+10% damage, -3% speed",damage:.1,speed:-.03}],
eyes:[{id:"eye",name:"Eye",cost:2400,desc:"+1.5% crit",crit:.015},{id:"hunterEye",name:"Hunter Eye",cost:18000,desc:"+3% crit",crit:.03},{id:"panicEye",name:"Panic Eye",cost:70000,desc:"+5% crit, +2% speed",crit:.05,speed:.02}]
};
const defaults={money:0,runDistance:0,bestDistance:0,totalDistance:0,speedLevel:0,incomeLevel:0,rockLevel:0,damageLevel:0,rebirths:0,kills:0,crates:0,bossKills:0,ownedGuns:["pistol"],gun:"pistol",ownedCompanions:[],boosts:{money:0,speed:0,damage:0},usedCodes:[],playerName:"CubePlayer",playTime:0,parts:{legs:{leg:2},arms:{arm:1},fungus:{},eyes:{}},toiletsUsed:0,trucksDestroyed:0};
let save=load(),paused=false,last=performance.now(),bullets=[],zombies=[],particles=[],crates=[],eventsIn=35,activeEvent=null,zombieTimer=0,bossTimer=75,crateTimer=25,shotCooldown=0,dashCooldown=0,screenShake=0,runTime=0,boulderSpawned=false,boulderWarning=false,keys={},pointer={x:800,y:300,down:false},toilet={active:false,x:760,y:70,w:68,h:68,time:0,occupied:0,next:120},truck=null,scenery=[];
const player={x:260,y:370,size:34,vx:0,vy:0,hidden:false},boulder={x:-180,y:387,radius:60,speed:0};
function cloneDefaults(){return JSON.parse(JSON.stringify(defaults))}
function load(){try{let raw=localStorage.getItem("ttdu.save.v3")||localStorage.getItem("ttdu.save.v2")||localStorage.getItem("ttdu.save.v1"),d=raw?JSON.parse(raw):null,base=cloneDefaults(),out={...base,...(d||{}),boosts:{...base.boosts,...((d&&d.boosts)||{})},parts:{...base.parts,...((d&&d.parts)||{})}};for(const k of Object.keys(base.parts))out.parts[k]={...base.parts[k],...((d&&d.parts&&d.parts[k])||{})};if(d?.skin&&!d.parts)out.money+=5000;return out}catch{return cloneDefaults()}}
function persist(){localStorage.setItem("ttdu.save.v3",JSON.stringify(save))}
const fmt=n=>{if(n<1000)return Math.floor(n).toLocaleString();let u=["K","M","B","T","Qa","Qi"],i=-1;while(n>=1000&&i<u.length-1){n/=1000;i++}return n.toFixed(n>=100?0:n>=10?1:2)+u[i]},dist=m=>m<1000?Math.floor(m)+" m":(m/1000).toFixed(m<10000?2:1)+" km";
const worldIndex=()=>{let i=0;worlds.forEach((w,n)=>{if(save.bestDistance>=w.need)i=n});return i},partCount=(cat,id)=>save.parts[cat]?.[id]||0;
function mutationStats(){let s={speed:0,damage:0,income:0,crit:.1,rate:0,dash:0,rock:0,autofire:0,total:0};for(const [cat,list] of Object.entries(parts))for(const p of list){let n=partCount(cat,p.id);s.total+=n;for(const k of Object.keys(s))if(p[k])s[k]+=p[k]*n}return s}
const speedBase=()=>1+save.speedLevel*.15,actualSpeed=()=>speedBase()*(1+save.rebirths*.05)*(save.boosts.speed>0?2:1)*(1+mutationStats().speed),incomeBase=()=>1+save.incomeLevel*2.5,moneyMult=()=>worlds[worldIndex()].mult*(save.boosts.money>0?2:1)*(activeEvent?.type==="money"?3:1)*(save.ownedCompanions.includes("goldBuddy")?1.15:1)*(1+mutationStats().income),income=()=>incomeBase()*moneyMult(),rebirthNeed=()=>Math.floor(1500*Math.pow(1.72,save.rebirths)),cost=(base,pow,lvl)=>Math.floor(base*Math.pow(pow,lvl));
function spend(c){if(save.money<c)return false;save.money-=c;return true}
function banner(t,d=3000){const b=$("eventBanner");b.textContent=t;b.hidden=false;clearTimeout(b._t);b._t=setTimeout(()=>b.hidden=true,d)}
function resetRun(){save.runDistance=0;runTime=0;boulderSpawned=false;boulderWarning=false;boulder.x=-180;zombies=[];bullets=[];crates=[];truck=null;toilet.active=false;toilet.occupied=0;toilet.next=120;player.hidden=false;player.x=260;player.y=370}
function die(title,text){paused=true;screenShake=18;resetRun();persist();$("deathTitle").textContent=title;$("deathText").textContent=text;$("crushMessage").hidden=false}
$("continueBtn").onclick=()=>{paused=false;$("crushMessage").hidden=true};
function spawnZombie(type,edge){let wi=worldIndex(),side=edge||(["right","top","bottom"][Math.floor(Math.random()*3)]),z={x:canvas.width+50,y:300+Math.random()*185,size:30,hp:2+Math.floor(wi/2)+Math.floor(save.rebirths/4),speed:42+wi*5,reward:(18+wi*10)*worlds[wi].mult,type:type||"normal",side};if(side==="top"){z.x=420+Math.random()*500;z.y=-45}else if(side==="bottom"){z.x=420+Math.random()*500;z.y=585}if(z.type==="fast"){z.size=23;z.speed*=1.85;z.hp*=.65}if(z.type==="tank"){z.size=48;z.speed*=.55;z.hp*=4;z.reward*=3}if(z.type==="exploder"){z.size=32;z.speed*=1.1;z.reward*=2}if(z.type==="splitter"){z.size=38;z.hp*=1.8;z.reward*=2.4}if(z.type==="shooter"){z.size=28;z.speed*=.65;z.hp*=1.4;z.shoot=1.4}if(z.type==="boss"){z.size=88;z.speed*=.45;z.hp*=18;z.reward*=18}z.maxHp=z.hp;zombies.push(z)}
function fire(tx,ty,auto=false){if(paused||shotCooldown>0||player.hidden)return;let g=guns[save.gun],m=mutationStats(),px=player.x+player.size/2,py=player.y+player.size/2,base=Math.atan2(ty-py,tx-px),rate=Math.max(.025,g.rate*(1-m.rate));for(let i=0;i<g.pellets;i++){let a=base+(Math.random()-.5)*g.spread;bullets.push({x:px,y:py,vx:Math.cos(a)*g.speed,vy:Math.sin(a)*g.speed,life:1.7,damage:g.damage*(1+save.damageLevel*.25)*(save.boosts.damage>0?2:1)*(1+m.damage),pierce:g.pierce,blast:g.blast||0,color:g.color,enemy:false})}shotCooldown=rate;if(!auto)pointer.down=true}
function point(e){let r=canvas.getBoundingClientRect();pointer.x=(e.clientX-r.left)*canvas.width/r.width;pointer.y=(e.clientY-r.top)*canvas.height/r.height}
canvas.addEventListener("pointerdown",e=>{point(e);pointer.down=true;fire(pointer.x,pointer.y)});canvas.addEventListener("pointermove",point);window.addEventListener("pointerup",()=>pointer.down=false);
window.addEventListener("keydown",e=>{keys[e.key.toLowerCase()]=true;if(e.code==="Space"){e.preventDefault();dash()}});window.addEventListener("keyup",e=>keys[e.key.toLowerCase()]=false);
document.querySelectorAll("[data-move]").forEach(b=>{let k=b.dataset.move;b.addEventListener("pointerdown",()=>keys[k]=true);b.addEventListener("pointerup",()=>keys[k]=false);b.addEventListener("pointerleave",()=>keys[k]=false)});
function dash(){if(dashCooldown>0||paused||player.hidden)return;player.x=Math.min(440,player.x+90*(1+mutationStats().dash));dashCooldown=6;screenShake=4;banner("DASH!")};$("dashBtn").onclick=dash;
function event(){let choices=[{type:"money",name:"MONEY STORM: 3x money",time:25},{type:"speed",name:"SPEED SURGE",time:20},{type:"horde",name:"ZOMBIE HORDE",time:22},{type:"freeze",name:"THE BOULDER FORGOT HOW TO MOVE",time:15},{type:"lucky",name:"LUCKY DAY: more crates",time:20},{type:"chicken",name:"CHICKEN RAIN. DO NOT ASK.",time:14},{type:"tax",name:"TAX COLLECTOR INBOUND",time:12}];activeEvent=choices[Math.floor(Math.random()*choices.length)];banner(activeEvent.name)}
function spawnCrate(){crates.push({x:canvas.width+20,y:330+Math.random()*150,size:28})}
function startToilet(){if(toilet.active||toilet.occupied>0)return;toilet.active=true;toilet.time=10;toilet.x=700+Math.random()*170;toilet.y=62;$("toiletTimer").hidden=false;banner("BATHROOM EMERGENCY! GET TO THE TOILET!",3500)}
function startTruck(){if(truck)return;truck={x:1030,y:310+Math.random()*155,w:150,h:62,hp:70+worldIndex()*15,speed:360};banner("HONK!!! SHOOT THE TRUCK OR GET FLATTENED!",3500)}
function spawnScenery(){if(scenery.length>14)return;let t=["tree","sign","house","rock"][Math.floor(Math.random()*4)];scenery.push({type:t,x:1000+Math.random()*200,y:t==="tree"?360+Math.random()*50:390+Math.random()*35})}
function update(dt){if(paused)return;runTime+=dt;save.playTime+=dt;shotCooldown=Math.max(0,shotCooldown-dt);dashCooldown=Math.max(0,dashCooldown-dt);Object.keys(save.boosts).forEach(k=>save.boosts[k]=Math.max(0,save.boosts[k]-dt));
if(pointer.down&&guns[save.gun].rate<.2)fire(pointer.x,pointer.y);let mx=(keys.d||keys.arrowright||keys.right?1:0)-(keys.a||keys.arrowleft||keys.left?1:0),my=(keys.s||keys.arrowdown||keys.down?1:0)-(keys.w||keys.arrowup||keys.up?1:0);if(toilet.occupied>0){toilet.occupied-=dt;player.hidden=true;if(toilet.occupied<=0){player.hidden=false;toilet.active=false;$("toiletTimer").hidden=true;banner("FLUSH! CRISIS SURVIVED");save.toiletsUsed++}}else{player.vx+=(mx*135-player.vx)*Math.min(1,dt*8);player.vy+=(my*190-player.vy)*Math.min(1,dt*8);player.x=Math.max(180,Math.min(440,player.x+player.vx*dt));player.y=Math.max(62,Math.min(478-player.size,player.y+player.vy*dt))}
if(runTime>25&&!boulderWarning){boulderWarning=true;banner("THE BOULDER ARRIVES IN 5 SECONDS")};if(runTime>=30&&!boulderSpawned){boulderSpawned=true;boulder.x=player.x-(650+save.rockLevel*55)-boulder.radius;boulder.y=player.y+player.size/2;boulder.speed=6;screenShake=8;banner("THE BOULDER HAS STARTED ROLLING!")}
let gain=actualSpeed()*(activeEvent?.type==="speed"?1.5:1)*18*dt;save.runDistance+=gain;save.totalDistance+=gain;save.bestDistance=Math.max(save.bestDistance,save.runDistance);save.money+=income()*dt;
if(boulderSpawned){boulder.y+=(player.y+player.size/2-boulder.y)*Math.min(1,dt*8);if(activeEvent?.type!=="freeze"){let chase=(6+Math.max(0,runTime-30)*.075+save.rebirths*.22)*(1+mutationStats().rock);boulder.speed=chase;boulder.x+=chase*dt}if(boulder.x+boulder.radius>=player.x)die("CRUSHED BY THE BIG ROCK","It followed your Y position. There was never an escape.")}
eventsIn-=dt;if(eventsIn<=0){event();eventsIn=45+Math.random()*30}if(activeEvent&&(activeEvent.time-=dt)<=0)activeEvent=null;
toilet.next-=dt;if(toilet.next<=0){startToilet();toilet.next=120}if(toilet.active&&toilet.occupied<=0){toilet.time-=dt;$("toiletTimer").textContent="🚽 HOLD IT: "+Math.ceil(toilet.time)+"s";if(!player.hidden&&player.x<toilet.x+toilet.w&&player.x+player.size>toilet.x&&player.y<toilet.y+toilet.h&&player.y+player.size>toilet.y){toilet.occupied=5;$("toiletTimer").textContent="OCCUPIED: 5s";banner("THE CUBE IS BUSY")};if(toilet.time<=0)die("YOU COULDN'T HOLD IT","Cause of death: catastrophic embarrassment.")}
if(!truck&&runTime>40&&Math.random()<dt/110)startTruck();if(truck){truck.x-=truck.speed*dt;if(truck.x<player.x+player.size&&truck.x+truck.w>player.x&&Math.abs(truck.y-player.y)<65)die("FLATTENED BY A TRUCK","The horn was not decorative.");if(truck.x+truck.w<0)truck=null}
zombieTimer-=dt;if(zombieTimer<=0){let r=Math.random(),t=r<.1?"fast":r<.18?"tank":r<.25?"exploder":r<.31?"splitter":r<.37?"shooter":"normal";spawnZombie(t);zombieTimer=activeEvent?.type==="horde"?.33:Math.max(.68,2-worldIndex()*.09)}bossTimer-=dt;if(bossTimer<=0){spawnZombie("boss","right");banner("BOSS ZOMBIE!");bossTimer=90}crateTimer-=dt;if(crateTimer<=0){spawnCrate();crateTimer=activeEvent?.type==="lucky"?8:28+Math.random()*18}if(Math.random()<dt*.45)spawnScenery();
bullets.forEach(b=>{b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt});bullets=bullets.filter(b=>b.life>0&&b.x>-50&&b.x<1050&&b.y>-60&&b.y<600);
zombies.forEach(z=>{let a=Math.atan2(player.y-z.y,player.x-z.x);z.x+=Math.cos(a)*z.speed*dt;z.y+=Math.sin(a)*z.speed*dt;if(z.type==="shooter"&&(z.shoot-=dt)<=0){let aa=Math.atan2(player.y-z.y,player.x-z.x);bullets.push({x:z.x,y:z.y,vx:Math.cos(aa)*300,vy:Math.sin(aa)*300,life:3,damage:0,pierce:0,blast:0,color:"#ff5555",enemy:true});z.shoot=1.8}});
for(const b of bullets){if(b.enemy){if(!player.hidden&&Math.hypot(b.x-(player.x+17),b.y-(player.y+17))<24){save.money=Math.max(0,save.money-income()*5);b.life=0;screenShake=4}continue}if(truck&&b.x>truck.x&&b.x<truck.x+truck.w&&b.y>truck.y-truck.h/2&&b.y<truck.y+truck.h/2){truck.hp-=b.damage;b.life=0;if(truck.hp<=0){save.money+=income()*100;save.trucksDestroyed++;banner("TRUCK DESTROYED! ABSURD PROFIT!");truck=null}}for(const z of zombies){if(z.hp<=0||b.life<=0)continue;if(Math.hypot(b.x-z.x,b.y-z.y)<z.size/2+6){let crit=Math.random()<mutationStats().crit;z.hp-=b.damage*(crit?2:1);if(b.blast){for(const o of zombies)if(Math.hypot(o.x-z.x,o.y-z.y)<b.blast)o.hp-=b.damage*.65}if(b.pierce>0)b.pierce--;else b.life=0;if(z.hp<=0){save.kills++;save.money+=z.reward;if(z.type==="boss")save.bossKills++;if(z.type==="exploder")for(const o of zombies)if(o!==z&&Math.hypot(o.x-z.x,o.y-z.y)<110)o.hp-=4;if(z.type==="splitter")for(let i=0;i<2;i++)zombies.push({...z,type:"fast",size:18,hp:1,maxHp:1,x:z.x+Math.random()*25,y:z.y+(Math.random()-.5)*30,reward:z.reward*.25});for(let i=0;i<8;i++)particles.push({x:z.x,y:z.y,vx:(Math.random()-.5)*150,vy:(Math.random()-.5)*150,life:.45})}}}}
zombies=zombies.filter(z=>z.hp>0&&z.x>-100&&z.y>-100&&z.y<640);for(const z of zombies){if(!player.hidden&&Math.abs(z.x-player.x)<(z.size+player.size)/2&&Math.abs(z.y-player.y)<(z.size+player.size)/2){let loss=Math.max(10,income()*3)*(save.ownedCompanions.includes("medicBuddy")?.5:1);save.money=Math.max(0,save.money-loss);z.hp=0;screenShake=7}}
crates.forEach(c=>c.x-=120*dt);for(const c of crates){if(!player.hidden&&Math.abs(c.x-player.x)<45&&Math.abs(c.y-player.y)<50){save.crates++;save.money+=income()*20;c.got=true;banner("SUPPLY CRATE! +$"+fmt(income()*20))}}crates=crates.filter(c=>!c.got&&c.x>-40);
let m=mutationStats();if(save.ownedCompanions.includes("blueBuddy")&&zombies.length&&Math.random()<dt*1.2){let z=zombies.reduce((a,b)=>b.x<a.x?b:a,zombies[0]);fire(z.x,z.y,true)}if(m.autofire&&zombies.length&&Math.random()<dt*m.autofire){let z=zombies[Math.floor(Math.random()*zombies.length)];shotCooldown=0;fire(z.x,z.y,true)}
scenery.forEach(s=>s.x-=55*dt);scenery=scenery.filter(s=>s.x>-100);particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt});particles=particles.filter(p=>p.life>0)}
function drawLeg(c,x,y,angle,len=20){c.save();c.translate(x,y);c.rotate(angle);c.strokeStyle="#2d2d35";c.lineWidth=6;c.beginPath();c.moveTo(0,0);c.lineTo(0,len);c.stroke();c.fillStyle="#111";c.fillRect(-7,len-2,14,6);c.restore()}
function drawExperiment(c,x,y,size,aimX,aimY,time){let m=mutationStats(),walk=Math.sin(time*.012)*5,legN=Math.min(16,Object.values(save.parts.legs).reduce((a,b)=>a+b,0)),armN=Math.min(16,Object.values(save.parts.arms).reduce((a,b)=>a+b,0)),fungusN=Math.min(18,Object.values(save.parts.fungus).reduce((a,b)=>a+b,0)),eyeN=Math.min(24,Object.values(save.parts.eyes).reduce((a,b)=>a+b,0)),cx=x+size/2,cy=y+size/2,aim=Math.atan2(aimY-cy,aimX-cx);
for(let i=0;i<legN;i++){let side=i%4,off=((i%4)-1.5)*7;if(side===0)drawLeg(c,cx+off,y+size,walk*.05,18);else if(side===1)drawLeg(c,x,cy+off,Math.PI/2+walk*.03,18);else if(side===2)drawLeg(c,cx+off,y,Math.PI+walk*.05,18);else drawLeg(c,x+size,cy+off,-Math.PI/2+walk*.03,18)}
for(let i=0;i<fungusN;i++){let a=i*2.399,rad=size*.55+(i%3)*8,fx=cx+Math.cos(a)*rad,fy=cy+Math.sin(a)*rad;c.fillStyle=i%3===0?"#6ef28a":"#4bcf66";c.fillRect(fx-6,fy-6,12,12);c.strokeStyle="#111";c.strokeRect(fx-6,fy-6,12,12)}
c.fillStyle="#4f93ff";c.fillRect(x,y,size,size);c.strokeStyle="#111";c.lineWidth=2;c.strokeRect(x,y,size,size);
for(let i=0;i<eyeN;i++){let a=i*2.1,rad=8+(i%3)*9,ex=cx+Math.cos(a)*rad,ey=cy+Math.sin(a)*rad;c.font="15px serif";c.fillText(i%4===0?"👀":"👁️",ex-8,ey+5)}
for(let i=0;i<armN;i++){let a=i===0?aim:(i/Math.max(1,armN))*Math.PI*2+time*.0003,ax=cx+Math.cos(a)*size*.45,ay=cy+Math.sin(a)*size*.45;c.strokeStyle=i===0?"#222":"#4b3c5a";c.lineWidth=7;c.beginPath();c.moveTo(ax,ay);c.lineTo(ax+Math.cos(a)*28,ay+Math.sin(a)*28);c.stroke();if(i===0){c.save();c.translate(ax+Math.cos(a)*30,ay+Math.sin(a)*30);c.rotate(a);c.fillStyle="#181818";c.fillRect(0,-5,28,10);c.restore()}}
return m}
function draw(){let w=worlds[worldIndex()],t=performance.now();ctx.save();if(screenShake>0){ctx.translate((Math.random()-.5)*screenShake,(Math.random()-.5)*screenShake);screenShake*=.84}ctx.fillStyle=w.sky;ctx.fillRect(0,0,960,540);ctx.fillStyle=w.ground;ctx.fillRect(0,420,960,120);ctx.fillStyle="rgba(255,255,255,.55)";for(let i=0;i<10;i++)ctx.fillRect(i*170-(save.runDistance*.5)%170,455,80,5);
scenery.forEach(s=>{if(s.type==="tree"){ctx.fillStyle="#6b4226";ctx.fillRect(s.x,s.y-50,10,55);ctx.fillStyle="#256b32";ctx.beginPath();ctx.arc(s.x+5,s.y-62,28,0,Math.PI*2);ctx.fill()}else if(s.type==="sign"){ctx.fillStyle="#6b4226";ctx.fillRect(s.x,s.y-35,8,40);ctx.fillStyle="#eee";ctx.fillRect(s.x-18,s.y-55,45,22);ctx.fillStyle="#111";ctx.font="10px Arial";ctx.fillText("WHY",s.x-7,s.y-40)}else if(s.type==="house"){ctx.fillStyle="#a15c3a";ctx.fillRect(s.x,s.y-45,55,45);ctx.fillStyle="#702c2c";ctx.beginPath();ctx.moveTo(s.x-8,s.y-45);ctx.lineTo(s.x+27,s.y-75);ctx.lineTo(s.x+63,s.y-45);ctx.fill()}else{ctx.fillStyle="#777";ctx.beginPath();ctx.arc(s.x,s.y,15,0,Math.PI*2);ctx.fill()}});
if(toilet.active){ctx.fillStyle="#f5f5f5";ctx.fillRect(toilet.x,toilet.y+18,58,42);ctx.fillRect(toilet.x+5,toilet.y,48,24);ctx.fillStyle="#79cfff";ctx.beginPath();ctx.ellipse(toilet.x+29,toilet.y+38,20,11,0,0,Math.PI*2);ctx.fill();ctx.fillStyle="#111";ctx.font="12px Arial";ctx.fillText("TOILET",toilet.x+8,toilet.y+76)}
if(boulderSpawned){ctx.fillStyle="#666";ctx.beginPath();ctx.arc(boulder.x,boulder.y,boulder.radius,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#333";ctx.lineWidth=5;ctx.stroke()}
if(!player.hidden)drawExperiment(ctx,player.x,player.y,player.size,pointer.x,pointer.y,t);
let ang=t/600;save.ownedCompanions.forEach((id,i)=>{ctx.fillStyle=id==="goldBuddy"?"#ffd700":id==="medicBuddy"?"#fff":"#55aaff";ctx.fillRect(player.x+Math.cos(ang+i*2.1)*55,player.y+Math.sin(ang+i*2.1)*38,14,14)});
bullets.forEach(b=>{ctx.fillStyle=b.color||"#ffeb3b";ctx.beginPath();ctx.arc(b.x,b.y,b.enemy?6:5,0,Math.PI*2);ctx.fill()});crates.forEach(c=>{ctx.fillStyle="#9b6b32";ctx.fillRect(c.x-14,c.y-14,28,28);ctx.strokeStyle="#fff";ctx.strokeRect(c.x-14,c.y-14,28,28)});
zombies.forEach(z=>{ctx.fillStyle=z.type==="fast"?"#79d65a":z.type==="tank"?"#295c31":z.type==="exploder"?"#d6a33c":z.type==="boss"?"#7d1f1f":z.type==="splitter"?"#a35bd6":z.type==="shooter"?"#438f9d":"#3f9b45";ctx.fillRect(z.x-z.size/2,z.y-z.size/2,z.size,z.size);ctx.fillStyle="#111";ctx.fillRect(z.x-8,z.y-8,5,5);ctx.fillRect(z.x+3,z.y-8,5,5);ctx.fillStyle="#b00";ctx.fillRect(z.x-z.size/2,z.y-z.size/2-8,z.size,4);ctx.fillStyle="#0f0";ctx.fillRect(z.x-z.size/2,z.y-z.size/2-8,z.size*(z.hp/z.maxHp),4)});
if(truck){ctx.fillStyle="#d83b32";ctx.fillRect(truck.x,truck.y-truck.h/2,truck.w,truck.h);ctx.fillStyle="#eee";ctx.fillRect(truck.x+90,truck.y-truck.h/2+8,45,26);ctx.fillStyle="#111";ctx.beginPath();ctx.arc(truck.x+30,truck.y+truck.h/2,14,0,Math.PI*2);ctx.arc(truck.x+115,truck.y+truck.h/2,14,0,Math.PI*2);ctx.fill();ctx.fillStyle="#fff";ctx.font="16px Arial";ctx.fillText("BAD TRUCK",truck.x+16,truck.y+5);ctx.fillStyle="#111";ctx.fillText(Math.max(0,Math.ceil(truck.hp))+" HP",truck.x+45,truck.y-22)}
particles.forEach(p=>{ctx.fillStyle="#ffe066";ctx.fillRect(p.x,p.y,4,4)});ctx.fillStyle="rgba(0,0,0,.65)";ctx.fillRect(10,10,405,92);ctx.fillStyle="#fff";ctx.font="17px Arial";ctx.fillText(w.name+"  x"+w.mult+" money",20,35);ctx.fillText(boulderSpawned?"Boulder gap: "+Math.max(0,Math.floor(player.x-boulder.x-boulder.radius))+" px":"Boulder in: "+Math.max(0,Math.ceil(30-runTime))+"s",20,60);ctx.fillText("Run: "+dist(save.runDistance)+"  Gun: "+guns[save.gun].name,20,85);ctx.restore()}
function ui(){let m=mutationStats();$("money").textContent=fmt(save.money);$("distance").textContent=dist(save.runDistance);$("speedStat").textContent=actualSpeed().toFixed(2);$("worldStat").textContent=(worldIndex()+1)+" - "+worlds[worldIndex()].name;$("rebirthStat").textContent=save.rebirths;$("killStat").textContent=save.kills;let sc=cost(25,1.55,save.speedLevel),ic=cost(35,1.58,save.incomeLevel),rc=cost(60,1.62,save.rockLevel),dc=cost(80,1.6,save.damageLevel);$("upgradeSpeed").textContent=`Speed Lv ${save.speedLevel} - $${fmt(sc)}`;$("upgradeIncome").textContent=`Money/sec Lv ${save.incomeLevel} - $${fmt(ic)}`;$("upgradeRock").textContent=`Rock Gap Lv ${save.rockLevel} - $${fmt(rc)}`;$("upgradeDamage").textContent=`Damage Lv ${save.damageLevel} - $${fmt(dc)}`;$("rebirthBtn").textContent=`Rebirth at ${dist(rebirthNeed())}`;$("rebirthBtn").disabled=save.runDistance<rebirthNeed();$("rockInfo").textContent="Rock starts at 30s and copies your Y movement.";let ab=Object.entries(save.boosts).filter(([,v])=>v>0).map(([k,v])=>`${k} ${Math.ceil(v)}s`).join(", ");$("boostInfo").textContent=ab?"Boosts: "+ab:"Boosts: none";$("challengeInfo").textContent=`Toilet in ~${Math.max(0,Math.ceil(toilet.next))}s | Trucks destroyed ${save.trucksDestroyed}`;$("stabilityInfo").textContent=`Experiment stability: ${m.total<5?"QUESTIONABLE":m.total<12?"BAD":m.total<22?"HORRIBLE":"WHY IS IT ALIVE"}`;$("dashBtn").textContent=dashCooldown>0?`DASH ${dashCooldown.toFixed(1)}s`:"DASH";$("gunInfo").textContent=`Damage ${guns[save.gun].damage} | Fire rate ${guns[save.gun].rate}s`}
function loop(n){let dt=Math.min(.05,(n-last)/1000);last=n;update(dt);draw();ui();requestAnimationFrame(loop)}
function buyBtn(id,fn){$(id).onclick=fn}buyBtn("upgradeSpeed",()=>{let c=cost(25,1.55,save.speedLevel);if(spend(c))save.speedLevel++});buyBtn("upgradeIncome",()=>{let c=cost(35,1.58,save.incomeLevel);if(spend(c))save.incomeLevel++});buyBtn("upgradeRock",()=>{let c=cost(60,1.62,save.rockLevel);if(spend(c))save.rockLevel++});buyBtn("upgradeDamage",()=>{let c=cost(80,1.6,save.damageLevel);if(spend(c))save.damageLevel++});$("rebirthBtn").onclick=()=>{if(save.runDistance>=rebirthNeed()){save.rebirths++;resetRun();banner("REBIRTH! Permanent +5% speed")}};
function refreshGunSelect(){let s=$("gunSelect");s.innerHTML="";save.ownedGuns.forEach(id=>{if(!guns[id])return;let o=document.createElement("option");o.value=id;o.textContent=guns[id].name;s.appendChild(o)});if(!guns[save.gun])save.gun="pistol";s.value=save.gun}$("gunSelect").onchange=e=>{save.gun=e.target.value;persist()};refreshGunSelect();
function open(id){let d=$(id);if(typeof d.showModal==="function")d.showModal();else d.setAttribute("open","")}$("shopBtn").onclick=()=>{renderShop("guns");open("shopDialog")};$("editorBtn").onclick=()=>{renderEditor("legs");open("editorDialog")};$("codesBtn").onclick=()=>open("codesDialog");$("leaderboardBtn").onclick=()=>{$("playerName").value=save.playerName;open("leaderboardDialog");loadScores()};$("statsBtn").onclick=()=>{renderStats();open("statsDialog")};$("helpBtn").onclick=()=>open("helpDialog");document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>{let d=$(b.dataset.close);typeof d.close==="function"?d.close():d.removeAttribute("open")});document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>renderShop(b.dataset.tab));document.querySelectorAll("[data-editor]").forEach(b=>b.onclick=()=>renderEditor(b.dataset.editor));
function renderShop(tab){let c=$("shopContent");c.innerHTML="";let list=tab==="guns"?Object.entries(guns).map(([id,x])=>({...x,id,type:"gun"})):tab==="boosts"?boosts.map(x=>({...x,type:"boost"})):companions.map(x=>({...x,type:"comp"}));list.forEach(x=>{let d=document.createElement("div");d.className="shop-item";d.innerHTML=`<b>${x.name}</b><p>${x.desc||("Cost: $"+fmt(x.cost))}</p>`;let b=document.createElement("button");if(x.type==="gun"){let own=save.ownedGuns.includes(x.id);b.textContent=own?(save.gun===x.id?"Equipped":"Equip"):"Buy $"+fmt(x.cost);b.disabled=save.gun===x.id;b.onclick=()=>{if(!own){if(!spend(x.cost))return;save.ownedGuns.push(x.id)}save.gun=x.id;refreshGunSelect();renderShop(tab)}}else if(x.type==="boost"){b.textContent="Buy $"+fmt(x.cost);b.onclick=()=>{if(spend(x.cost)){save.boosts[x.id]+=x.duration;renderShop(tab)}}}else{let own=save.ownedCompanions.includes(x.id);b.textContent=own?"Owned":"Buy $"+fmt(x.cost);b.disabled=own;b.onclick=()=>{if(spend(x.cost)){save.ownedCompanions.push(x.id);renderShop(tab)}}}d.appendChild(b);c.appendChild(d)})}
function renderEditor(cat){let c=$("editorParts");c.innerHTML="";parts[cat].forEach(p=>{let n=partCount(cat,p.id),max=cat==="fungus"||cat==="eyes"?24:16,d=document.createElement("div");d.className="shop-item";d.innerHTML=`<b>${p.name}</b><p>${p.desc}</p><p class="part-count">Attached: ${n}/${max}</p>`;let b=document.createElement("button");b.textContent=n>=max?"Maximum":"Buy + Attach $"+fmt(Math.floor(p.cost*Math.pow(1.28,n)));b.disabled=n>=max;b.onclick=()=>{let price=Math.floor(p.cost*Math.pow(1.28,n));if(spend(price)){save.parts[cat][p.id]=n+1;renderEditor(cat)}};let r=document.createElement("button");r.textContent="Remove one (no refund)";r.disabled=n<=0;r.onclick=()=>{save.parts[cat][p.id]=Math.max(0,n-1);renderEditor(cat)};d.append(b,r);c.appendChild(d)});let m=mutationStats();$("editorStats").textContent=`Parts: ${m.total}\nSpeed: ${(m.speed*100).toFixed(1)}%\nDamage: ${(m.damage*100).toFixed(1)}%\nIncome: ${(m.income*100).toFixed(1)}%\nCrit chance: ${(m.crit*100).toFixed(1)}%`;drawEditor()}
function drawEditor(){ectx.clearRect(0,0,420,320);ectx.fillStyle="#101018";ectx.fillRect(0,0,420,320);drawExperiment(ectx,180,135,58,360,150,performance.now());ectx.fillStyle="#fff";ectx.font="15px Arial";ectx.fillText("LIVE SPECIMEN PREVIEW",118,28)}
function renderStats(){let m=mutationStats();$("statsContent").innerHTML=`<p>Best distance: ${dist(save.bestDistance)}</p><p>Total distance: ${dist(save.totalDistance)}</p><p>Zombies defeated: ${save.kills}</p><p>Bosses defeated: ${save.bossKills}</p><p>Crates collected: ${save.crates}</p><p>Toilet emergencies survived: ${save.toiletsUsed}</p><p>Trucks destroyed: ${save.trucksDestroyed}</p><p>Play time: ${Math.floor(save.playTime/60)} minutes</p><p>Guns: ${save.ownedGuns.length}/${Object.keys(guns).length}</p><p>Mutation parts: ${m.total}</p>`}
const codeRewards={FIRSTSTEP:{money:2500,msg:"+$2,500"},BIGROCK:{money:5000,rock:1,msg:"+$5,000 and +1 rock level"},CUBEPOWER:{money:10000,speed:1,msg:"+$10,000 and +1 speed level"},GUNRUNNER:{money:8000,damage:1,msg:"+$8,000 and +1 damage level"},GOBLIN:{money:25000,eye:2,msg:"+$25,000 and two eyes"}};$("redeemCode").onclick=()=>{let code=$("codeInput").value.trim().toUpperCase(),o=$("codeMessage"),r=codeRewards[code];if(!r)return o.textContent="Invalid code.";if(save.usedCodes.includes(code))return o.textContent="Already used.";save.money+=r.money||0;save.rockLevel+=r.rock||0;save.speedLevel+=r.speed||0;save.damageLevel+=r.damage||0;if(r.eye)save.parts.eyes.eye=(save.parts.eyes.eye||0)+r.eye;save.usedCodes.push(code);o.textContent="Redeemed: "+r.msg;persist()};
async function loadScores(){let l=$("leaderboardList"),m=$("leaderboardMessage");l.innerHTML="";m.textContent="Loading...";try{let r=await fetch(`${SUPABASE_URL}/rest/v1/${SCORE_TABLE}?select=name,distance,rebirths&order=distance.desc&limit=20`,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`}});if(!r.ok)throw Error();let rows=await r.json();rows.forEach(x=>{let li=document.createElement("li");li.textContent=`${x.name} — ${dist(Number(x.distance))} — ${x.rebirths} rebirths`;l.appendChild(li)});m.textContent=rows.length?"Top distances":"No scores yet."}catch{m.textContent="Leaderboard table is not ready."}}
$("submitScore").onclick=async()=>{let name=$("playerName").value.trim().slice(0,20)||"CubePlayer";save.playerName=name;try{let r=await fetch(`${SUPABASE_URL}/rest/v1/${SCORE_TABLE}`,{method:"POST",headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,"Content-Type":"application/json",Prefer:"return=minimal"},body:JSON.stringify({name,distance:Math.floor(save.bestDistance),rebirths:save.rebirths,money:Math.floor(save.money)})});if(!r.ok)throw Error();$("leaderboardMessage").textContent="Score submitted!";loadScores()}catch{$("leaderboardMessage").textContent="Could not submit."}};$("refreshScores").onclick=loadScores;
window.addEventListener("beforeunload",persist);setInterval(persist,5000);requestAnimationFrame(loop);
})();
